services:
  walleye-pi:
    build:
      context: .
    ports:
      - 5800:5800
    volumes:
      - /home/orangepi/walleye_data:/app/walleye_data
      - type: bind
        source: /dev
        target: /dev
    develop:
      watch:
        - action: rebuild
          path: .
    privileged: true
volumes:
  walleye_data:
